### ISSUE TITLE
traQに投稿

### ISSUE THREAD

**Issue by itt828** [traP-jp/h24s_17-backend#13]
- POST /checkinリクエストが送られた
- raspiから写真が送られた

を条件にtraQに写真と誰が訪問したかを投稿する

## やること
- traQ botを作成
- 条件が満たされたことを検知する

**Comment by itt828** [comment]
1. POST /standが叩かれる
  - headerにX-Raspi-Secret
  - bodyに画像が含まれる
  - RASPI_SECRETが一致
3. QRが読みこまれていることをDBを叩いて確認
4. BOTによりtraQに投稿

**Comment by H1rono** [comment]
環境変数`RASPI_SECRET`を読んで`State`に含める必要がある(`macSecret`と同様)
